[phases.setup]
nixPkgs = ["python311", "nodejs_20", "uv"]

[phases.install]
cmds = [
  "uv pip install --system -r app/backend/requirements.txt",
  "cd app/frontend && npm install"
]

[phases.build]
cmds = [
  "cd app/frontend && npm run build:prod",
  "mkdir -p app/backend/static_frontend",
  "cp -r app/frontend/dist/. app/backend/static_frontend/"
]
